Added express framework, but for some reason still not getting the calendar to show up. Still getting the following three errors:  Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/. 2http://localhost:3000/bower_components/jquery/jquery.js Failed to load resource: the server responded with a status of 404 (Not Found) calendar.js:432 Uncaught TypeError: string is not a function